all: hello hallo age

hello: main_hello.c
	gcc main_hello.c -o hello

hallo: main_hallo.c
	gcc main_hallo.c -o hallo

age: main_age.c
	gcc main_age.c -o age

clean: 
	rm -f hello
	rm -f hallo
	rm -f age
